repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        args: [ "--line-length=88" ]
        exclude: |
          (?x)^(
            venv/
          )/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        name: ruff
        args: [ "--fix" ]
        exclude: |
          (?x)^(
            venv/
          )/